#!/usr/bin/expect -f
set timeout 60
set password "Mahim@9898@@"

spawn ssh -o ServerAliveInterval=30  root@187.124.113.85
expect {
    "yes/no" { send "yes\r"; exp_continue }
    "password:" { send "$password\r" }
}

expect "$ "
send "echo \"@reboot export PATH=\\\$PATH && cd /var/www/ai4you.mindsetai.cloud && npx pm2 resurrect\" > mycron\r"
expect "$ "

send "crontab mycron\r"
expect "$ "

send "rm mycron\r"
expect "$ "

send "crontab -l\r"
expect "$ "

send "exit\r"
expect eof
